/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Usuarios;

/**
 *
 * @author Admin
 */
public class Registro_Docente extends javax.swing.JPanel {

    /**
     * Creates new form REGISTRO_DOCENTE
     */
    public Registro_Docente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NOMBRE_TEXT = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        MATRICULA_TEXT = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        TIPO_TEXT = new javax.swing.JLabel();
        TipoDocente = new javax.swing.JComboBox<>();
        CORREO_TEXT = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        GENERO_TEXT = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        REGISTRAR_BOTON = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(980, 530));
        setMinimumSize(new java.awt.Dimension(980, 530));
        setPreferredSize(new java.awt.Dimension(980, 530));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gotham", 3, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRO DE DOCENTES/ADMINISTRATIVOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        jLabel1.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>Estimado Docente/Administrativo<p>Registrate si vienes por primera vez a la Biblioteca de #LaMetro<html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 980, -1));

        NOMBRE_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        NOMBRE_TEXT.setText("Nombre");
        jPanel1.add(NOMBRE_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        jTextField2.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 320, -1));

        MATRICULA_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        MATRICULA_TEXT.setText("Num de Control");
        jPanel1.add(MATRICULA_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        jTextField3.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 320, -1));

        TIPO_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        TIPO_TEXT.setText("Tipo");
        jPanel1.add(TIPO_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 30));

        TipoDocente.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        TipoDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Docente", "Administrativo" }));
        jPanel1.add(TipoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 320, -1));

        CORREO_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        CORREO_TEXT.setText("<html>Correo<p>Institucional<hmtl>");
        jPanel1.add(CORREO_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 325, -1, 60));

        jTextField5.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 320, 30));

        GENERO_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        GENERO_TEXT.setText("Genero");
        jPanel1.add(GENERO_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 30));

        jTextField1.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 320, -1));

        REGISTRAR_BOTON.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        REGISTRAR_BOTON.setText("REGISTRARME");
        REGISTRAR_BOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRAR_BOTONActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTRAR_BOTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTRAR_BOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRAR_BOTONActionPerformed
        // REGISTRAR DOCENTES
    }//GEN-LAST:event_REGISTRAR_BOTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CORREO_TEXT;
    private javax.swing.JLabel GENERO_TEXT;
    private javax.swing.JLabel MATRICULA_TEXT;
    private javax.swing.JLabel NOMBRE_TEXT;
    private javax.swing.JButton REGISTRAR_BOTON;
    private javax.swing.JLabel TIPO_TEXT;
    private javax.swing.JComboBox<String> TipoDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
