
package Usuarios;

// @author dell

public class Registro_Alumno extends javax.swing.JPanel {

    /**
     * Creates new form Registro_Alumno
     */
    public Registro_Alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GENERO_TEXT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NOMBRE_TEXT = new javax.swing.JLabel();
        CARRERA_TEXT = new javax.swing.JLabel();
        CORREO_TEXT = new javax.swing.JLabel();
        MATRICULA_TEXT = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(980, 530));
        setMinimumSize(new java.awt.Dimension(980, 530));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(980, 530));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrate si vienes por primera vez a la Biblioteca de #LaMetro ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 980, -1));

        GENERO_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        GENERO_TEXT.setText("Genero");
        jPanel1.add(GENERO_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 30));

        jLabel3.setFont(new java.awt.Font("Gotham", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRO DE ALUMNO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        NOMBRE_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        NOMBRE_TEXT.setText("Nombre");
        jPanel1.add(NOMBRE_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        CARRERA_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        CARRERA_TEXT.setText("Carrera");
        jPanel1.add(CARRERA_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 30));

        CORREO_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        CORREO_TEXT.setText("<html>Correo <p>Institucional<hmtl>");
        jPanel1.add(CORREO_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 325, -1, 60));

        MATRICULA_TEXT.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        MATRICULA_TEXT.setText("Matricula");
        jPanel1.add(MATRICULA_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        jTextField1.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 320, -1));

        jTextField2.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 320, -1));

        jTextField3.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 320, -1));

        jTextField4.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 320, -1));

        jTextField5.setFont(new java.awt.Font("Gotham", 0, 25)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 320, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setText("REGISTRARME");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CARRERA_TEXT;
    private javax.swing.JLabel CORREO_TEXT;
    private javax.swing.JLabel GENERO_TEXT;
    private javax.swing.JLabel MATRICULA_TEXT;
    private javax.swing.JLabel NOMBRE_TEXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
